### ISSUE TITLE
[Web] - Implement nút check all khi xem báo cáo

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#20]
- Implement nút check all khi xem báo cáo
- Thêm image cho thiết bị bóng đèn
  ![capture1](https://cloud.githubusercontent.com/assets/6778102/8874928/aefd3f2a-323f-11e5-8bbc-7e9fe9cc63b6.PNG)

**Comment by doannguyenminhchi** [comment]
Có nút "Khắc phục tất cả" rồi
Thêm nút check all nữa chi cho nó rối.
Nếu muốn thì thay cái nút đó luôn.

**Comment by tranquang9a1** [comment]
OK
