### ISSUE TITLE
[Web] - Sửa giao diện tab trong trang chi tiết báo cáo

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#21]
Cần làm nổi bật 2 tab này lên. Để cho người dùng có thể biết click vào
![capture2](https://cloud.githubusercontent.com/assets/6778102/8874974/f4bf2848-323f-11e5-8221-b0f274250050.PNG)

**Comment by doannguyenminhchi** [comment]
Done

**Comment by tranquang9a1** [comment]
Done
