### ISSUE TITLE
[Web] - Giao diện bị bể khi xóa equipment

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#23]
Trong trang equipment, tất cả các confirm form đều bị bể.
- Khi tạo thiết bị
- Khi xóa thiết bị

![capture4](https://cloud.githubusercontent.com/assets/6778102/8875078/9775a1c0-3240-11e5-9408-14fb160cf8e3.PNG)

**Comment by hungtvse61019** [comment]
done
![image](https://cloud.githubusercontent.com/assets/12387243/8891008/dd1da5e6-3340-11e5-80de-a805e7e29c31.png)

**Comment by tranquang9a1** [comment]
Done
