### ISSUE TITLE
[Web] - Validate khi tạo thiết bị

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#24]
Thiết bị cần phải có tên
Form tạo thiết bị cần design lại.
- Để padding top 1 khoảng
- Thu nhỏ dư thừa của form 

![capture5](https://cloud.githubusercontent.com/assets/6778102/8875158/357fc396-3241-11e5-9d1b-f5eedeb15dd4.PNG)

**Comment by hungtvse61019** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/12387243/8890987/a424f182-333f-11e5-9f0e-a2c0cdf7876d.png)

**Comment by tranquang9a1** [comment]
Done
