### ISSUE TITLE
[Web] - Trang Phòng Học cần design lại 

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#25]
- Design lại tab cho nổi bật hơn
- Placeholder của ô search cần là từ có nghĩa ví dụ "Nhập loại phòng"
- Trạng thái là gì, nếu không cần thiết thì khỏi hiện
  ![capture6](https://cloud.githubusercontent.com/assets/6778102/8875198/9100ecae-3241-11e5-8efd-d9aed59f97c2.PNG)

**Comment by hungtvse61019** [comment]
- trạng thái là chỉ tình trạng phòng
  Done
  ![image](https://cloud.githubusercontent.com/assets/12387243/8889140/2b6ae122-32f7-11e5-9924-234ed0b1f8c6.png)

**Comment by tranquang9a1** [comment]
Done
