### ISSUE TITLE
[Web] - Sửa header table tab Loại Phòng, Trang phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#27]
Header là từ tiếng việt, có nghĩa

![capture7](https://cloud.githubusercontent.com/assets/6778102/8875255/faa62d9a-3241-11e5-969a-d5bdaff2ecee.PNG)

**Comment by doannguyenminhchi** [comment]
Done

**Comment by tranquang9a1** [comment]
Ở đâu ra quyền dev có thể close issue vậy

**Comment by tranquang9a1** [comment]
Done
