### ISSUE TITLE
[Web] - Đổi giao diện confirm box khi tạo loại phòng 

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#28]
Thống nhất sử dụng confirm box như bên dưới
![capture8](https://cloud.githubusercontent.com/assets/6778102/8875287/4d0f1470-3242-11e5-8e71-e6ac53e038cc.PNG)

Bỏ hết tất cả confirm là alert

**Comment by hungtvse61019** [comment]
Done

**Comment by tranquang9a1** [comment]
Close khi tất cả reference được close
