### ISSUE TITLE
[Web] - Sửa giao diện trang tạo loại phòng

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#29]
- Title là chữ tiếng việt, có dấu, có nghĩa
- Quạt thêm textbox nhập số lượng
- Mặc định số dãy bàn là 2
- Thanh scrollbar ở dưới chỉ hiện thị khi nào cần thiết
  ![capture9](https://cloud.githubusercontent.com/assets/6778102/8875370/f0733254-3242-11e5-847f-e7ea490b7a2f.PNG)

**Comment by hungtvse61019** [comment]
- Không quản lý quạt nên không cần phải có số lượng.
- Done
  ![image](https://cloud.githubusercontent.com/assets/12387243/8888799/fe3b224e-32e6-11e5-97fc-64f5b92d77a2.png)

**Comment by tranquang9a1** [comment]
Commit code phần này chưa 
Lên server check lại xem ?

**Comment by hungtvse61019** [comment]
Check lại đi

**Comment by tranquang9a1** [comment]
Lỗi hiển thị
- Từ trang quản lí loại phòng, ấn tạo loại phòng -> Chọn thông tin bất kì -> Sau đó nhấn Thoát
- Tiếp tục ấn tạo loại phòng, các thông tin đã chọn không bị clear.

![capture](https://cloud.githubusercontent.com/assets/6778102/8892712/0974ae66-3394-11e5-98b8-a3f112e01744.PNG)
- Nhập thông tin đúng, ấn tạo loại phòng -> Bể form

![capture1](https://cloud.githubusercontent.com/assets/6778102/8892715/16dbb874-3394-11e5-8c84-96eba2ebd137.PNG)

**Comment by hungtvse61019** [comment]
Đã Fix
