### ISSUE TITLE
[Web] - Check validate khi tạo loại phòng

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#30]
Tạo loại phòng, chọn máy lạnh, không nhập số lượng
![capture10](https://cloud.githubusercontent.com/assets/6778102/8875416/492ba89a-3243-11e5-8dd0-293154f36ed9.PNG)

Nhập tạo loại phòng -> Validate sai
![capture11](https://cloud.githubusercontent.com/assets/6778102/8875422/5227bfba-3243-11e5-9eea-4254724e5a0e.PNG)

**Comment by hungtvse61019** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/12387243/8888780/3c5c9626-32e6-11e5-92f2-cb4690be3480.png)

**Comment by tranquang9a1** [comment]
Reference bug https://github.com/tranquang9a1/ECRM/issues/28

Chuyển tất cả confirm box thành 1 kiểu duy nhất

**Comment by hungtvse61019** [comment]
Đã fix
![image](https://cloud.githubusercontent.com/assets/12387243/8890914/a257c544-333c-11e5-8683-470f5b00ecd9.png)

**Comment by tranquang9a1** [comment]
Sửa lỗi khi hiện confirm box thì tất cả các form đã hiện trước đó phải được ẩn đi

**Comment by hungtvse61019** [comment]
Bỏ
