### ISSUE TITLE
[Web] - Sửa giao diện trang tạo phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#31]
- Placeholder của số phòng là từ tiếng việt, có dấu, có nghĩa. VD: Nhập số phòng
- Nút chọn loại phòng cần làm nổi bật hơn, user có thể nhận biết
- Đổi tên nút "Thêm" thành "Tạo Phòng"

![capture12](https://cloud.githubusercontent.com/assets/6778102/8875506/d934d948-3243-11e5-831d-7f71091be2ae.PNG)

**Comment by hungtvse61019** [comment]
DOne

![image](https://cloud.githubusercontent.com/assets/12387243/8888775/0f5ed08a-32e6-11e5-8359-d33fca21344a.png)

**Comment by tranquang9a1** [comment]
![capture8](https://cloud.githubusercontent.com/assets/6778102/8889319/e3f91612-32fe-11e5-983d-57ce8ca2cf52.PNG)
- Nhập số phòng hay tên phòng ?
- Nút chọn loại phòng cần làm nổi bật hơn, user có thể nhận biết (Có thể đưa vào giữa, nằm giống như textbox tên phòng)
- Đổi tên nút "Thêm" thành "Tạo Phòng"

**Comment by hungtvse61019** [comment]
Đã Fix
![image](https://cloud.githubusercontent.com/assets/12387243/8890910/7e62c346-333c-11e5-916a-3bef2ea23734.png)

**Comment by tranquang9a1** [comment]
Close khi issue https://github.com/tranquang9a1/ECRM/issues/34 close

**Comment by hungtvse61019** [comment]
DOne
