### ISSUE TITLE
[Web] - Sửa giao diện trang chọn loại phòng thì tạo phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#32]
- Loại phòng mặc định là loại đầu tiên, không để như vậy
- Chưa chọn loại phòng thì phải bỏ phần khoảng trắng
- Giao diện lớn quá, màn hình nhỏ không thấy hết

![capture13](https://cloud.githubusercontent.com/assets/6778102/8875806/d4ee812a-3245-11e5-8b51-bbfae9940fe8.PNG)

**Comment by hungtvse61019** [comment]
done
![image](https://cloud.githubusercontent.com/assets/12387243/8888706/c769d4bc-32e2-11e5-86d6-2c2bda81b01d.png)

**Comment by tranquang9a1** [comment]
Reference bug https://github.com/tranquang9a1/ECRM/issues/34
