### ISSUE TITLE
[Web] - Sửa lỗi hiển thị khi chọn loại phòng

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#34]
![capture14](https://cloud.githubusercontent.com/assets/6778102/8875890/5af762c8-3246-11e5-929f-9fbe8ea4d031.PNG)
- Từ trang tạo phòng chọn loại phòng mới, rồi nhấn "Trở lại"
- Sau đó nhấn "Chọn loại phòng"
- Hệ thống phải load loại phòng hiện đang chọn
- Hiện tại đang load loại phòng lần cuối được chọn

![capture15](https://cloud.githubusercontent.com/assets/6778102/8875940/972742ea-3246-11e5-9d78-d5a720d13f51.PNG)

**Comment by hungtvse61019** [comment]
Done

**Comment by tranquang9a1** [comment]
Lỗi hiển thị tiếp theo
- Lần đầu tiên vào trang tạo phòng -> Ấn chọn loại phòng -> Loại phòng không được load sơ đồ

![capture5](https://cloud.githubusercontent.com/assets/6778102/8889283/0ab2c0f6-32fe-11e5-9102-fff04ff24321.PNG)
- Từ trang này (không làm bất cứ thao tác gì) ấn chọn -> Loại phòng chưa được chọn

![capture6](https://cloud.githubusercontent.com/assets/6778102/8889285/18061abe-32fe-11e5-8969-c74986d4b5da.PNG)
- Đổi tất cả chỉ dùng chung 1 alert như https://github.com/tranquang9a1/ECRM/issues/28

![capture7](https://cloud.githubusercontent.com/assets/6778102/8889288/44e5a96e-32fe-11e5-88c2-414c86e0d3cd.PNG)

**Comment by hungtvse61019** [comment]
Đã fix

**Comment by tranquang9a1** [comment]
Lỗi giao diện.
- Từ trang quản lí phòng học, Chọn sửa phòng học sau đó chọn Thoát.
- Lỗi hiển thị khi tiến hành tạo phòng học mới 

![capture1](https://cloud.githubusercontent.com/assets/6778102/8892688/691327d2-3392-11e5-8a8e-372211c1892b.PNG)
- Khi chưa có loại phòng thì nút phải thẳng hàng với textbox phía trên
- Từ form tạo phòng, ấn chọn loại phòng sau đó chọn Hủy

![capture2](https://cloud.githubusercontent.com/assets/6778102/8892693/a92677c0-3392-11e5-99d1-53f5bdce3c40.PNG)

-> Loại phòng được hiện ra mặc dù chưa được chọn
- Confirm form khi hiện ra phải ẩn các form trước đó

![capture3](https://cloud.githubusercontent.com/assets/6778102/8892696/cfdf0d3c-3392-11e5-9419-ce202c9487ee.PNG)

**Comment by hungtvse61019** [comment]
Đã Fix
![image](https://cloud.githubusercontent.com/assets/12387243/8923045/7bf02f4c-3515-11e5-84f3-07b1e12cdd71.png)

**Comment by tranquang9a1** [comment]
Commit chưa, lên server check lại ?

**Comment by hungtvse61019** [comment]
Bỏ
