### ISSUE TITLE
[Web] - Lỗi hiển thị khi sửa phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#36]
- Tại trang quản lí, chọn sửa phòng học

![capture17](https://cloud.githubusercontent.com/assets/6778102/8876047/5ca90378-3247-11e5-9595-2fd8ad9b42e9.PNG)

-> Nút X không tắt được form
- Chọn chỉnh sửa

![capture18](https://cloud.githubusercontent.com/assets/6778102/8876054/67f2345c-3247-11e5-8724-58b1c8f59083.PNG)

Không load loại phòng hiện tại của phòng này

**Comment by hungtvse61019** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/12387243/8888563/14f901d2-32dc-11e5-8359-d1ff2aaa6cb2.png)

**Comment by tranquang9a1** [comment]
![capture3](https://cloud.githubusercontent.com/assets/6778102/8889251/d9383de0-32fc-11e5-8b79-969ee436c3cd.PNG)

Tiếp tục sửa:
- Title phải có khoảng trắng, chuyển thành "Sơ đồ phòng xxxx"
- Xóa chữ sơ đồ ở dưới
- Thanh scrollbar chỉ hiện khi cần thiết

![capture4](https://cloud.githubusercontent.com/assets/6778102/8889255/1ec6875e-32fd-11e5-8098-9dd3634ab235.PNG)
- Bể form khi tiến hành sửa

**Comment by hungtvse61019** [comment]
- Bể form chưa fix đc.

![image](https://cloud.githubusercontent.com/assets/12387243/8890287/b55eebf2-3325-11e5-961c-d1c0967550f1.png)

**Comment by tranquang9a1** [comment]
Close khi form được fix

**Comment by tranquang9a1** [comment]
![image](https://cloud.githubusercontent.com/assets/6778102/8889255/1ec6875e-32fd-11e5-8098-9dd3634ab235.PNG)

@ChiDNMSE60717 fix lỗi bể giao diện

**Comment by doannguyenminhchi** [comment]
Sửa rồi!

**Comment by tranquang9a1** [comment]
Chưa test được

**Comment by tranquang9a1** [comment]
Done
