### ISSUE TITLE
[Web] - Lỗi khi search schedule

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#37]
- Tại ô search nhập 1 phòng học hoặc 1 giáo viên không có trong hệ thống
- Nhấn Search
- Lỗi

![capture19](https://cloud.githubusercontent.com/assets/6778102/8876122/dc9645f0-3247-11e5-9c72-7415302e6e9e.PNG)

**Comment by hungtvse61019** [comment]
Done

**Comment by tranquang9a1** [comment]
Lỗi phát sinh như sau:
- Tại trang schedule, nhập tên giáo viên hoặc phòng học không có trong hệ thống, ấn Search
  Server trả về lịch dạy ngày hôm đó ->> Sai
- Sau lúc đó, nếu có nhập đúng thì cũng không ra kết quả

Các bước như sau:

![capture1](https://cloud.githubusercontent.com/assets/6778102/8889242/4924d7c2-32fc-11e5-97bd-8053bffaf927.PNG)

Nhập giáo viên "4444"

![capture2](https://cloud.githubusercontent.com/assets/6778102/8889246/53fc0b0c-32fc-11e5-8e54-5b119b5ed5cd.PNG)

Sau đó tìm lịch phòng 213.
- Kết quả mong đợi là không có lịch
- Kết quả hiện tại là lịch của 403

<b> Lên Server để test chi tiết <b>

**Comment by hungtvse61019** [comment]
Đã validate nhập username hay phòng không có thì disable nút đi
![image](https://cloud.githubusercontent.com/assets/12387243/8889978/5668b9a4-3319-11e5-83a5-ab7a7c37634d.png)

**Comment by tranquang9a1** [comment]
Check lại validate cho phòng học

![capture10](https://cloud.githubusercontent.com/assets/6778102/8890174/bf10a5d2-3320-11e5-8c16-44d9ac28211a.PNG)

**Comment by hungtvse61019** [comment]
đã fix
![image](https://cloud.githubusercontent.com/assets/12387243/8890331/0f65e5ea-3328-11e5-9d6f-14d8d79fb9aa.png)
