### ISSUE TITLE
[Web] - Lỗi khi import schedule bằng tay

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#38]
-Tại trang import shedule, nhập như hình

![capture20](https://cloud.githubusercontent.com/assets/6778102/8876160/1a5061f0-3248-11e5-9bad-4fec368b2ca1.PNG)

-Nhấn Tạo
-Lỗi

**Comment by hungtvse61019** [comment]
Done

**Comment by tranquang9a1** [comment]
Done
