### ISSUE TITLE
[Web] - Sửa giao diện trang nhập lịch bằng tay

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#39]
- Thống nhất các button trong website chỉ sử dụng 1 màu
- Canh lề các textbox cho bằng nhau
- Phần checkbox, Khi nhấn vào label cũng phải check luôn checkbox

![capture20](https://cloud.githubusercontent.com/assets/6778102/8876226/96526ece-3248-11e5-8393-602279c6890d.PNG)

**Comment by hungtvse61019** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/12387243/8887874/2b9d1cfa-32c0-11e5-9046-e620686ad9d9.png)

**Comment by tranquang9a1** [comment]
Fix bug thì update source code lên để còn test. Để vậy ai confirm để close được

**Comment by hungtvse61019** [comment]
ok

**Comment by tranquang9a1** [comment]
Done
