### ISSUE TITLE
[Web] - Sửa giao diện phần import file schedule

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#40]
- Để padding top cho dễ nhìn thấy chữ.
- Button cả website chỉ 1 màu
- Chưa validate khi không chọn file mà nhấn import
  ![capture21](https://cloud.githubusercontent.com/assets/6778102/8876288/e9bedb7e-3248-11e5-9245-bf1c08fc2bef.PNG)

**Comment by hungtvse61019** [comment]
done
![image](https://cloud.githubusercontent.com/assets/12387243/8887864/6092d7a2-32bf-11e5-9f8c-17501a0ece32.png)

**Comment by tranquang9a1** [comment]
![6092d7a2-32bf-11e5-9f8c-17501a0ece32](https://cloud.githubusercontent.com/assets/6778102/8887879/44f85d0e-32c0-11e5-8900-772cb8d8db67.png)
- Thêm padding giữa chọn file và error message. Hiện tại gần quá.
- Sao lại có tiếng anh ở đây
- Lần sau làm xong thì chọn assignee lại cho dễ check
  ![capture](https://cloud.githubusercontent.com/assets/6778102/8887881/7843dcd8-32c0-11e5-8305-02c7e77bee1b.PNG)

**Comment by tranquang9a1** [comment]
Done
