### ISSUE TITLE
[Web] - Desgin lại giao diện trang user

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#41]
Left panel thì ok rồi - cần thiết cho giờ hiện tại của hệ thống lên cho dễ theo dõi
Phần tạo báo cáo
Không nên sử dụng cùng 1 kiểu giao diện trong 1 trang, gây rối mắt, khó coi

Design lại trang này
![capture22](https://cloud.githubusercontent.com/assets/6778102/8876520/6fd1313e-324a-11e5-912b-744cae7038b5.PNG)

**Comment by doannguyenminhchi** [comment]
Done

**Comment by tranquang9a1** [comment]
Done
