### ISSUE TITLE
[Web] - Sửa giao diện trang xem báo cáo

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#42]
![capture23](https://cloud.githubusercontent.com/assets/6778102/8876574/c23f9460-324a-11e5-8528-77ffca018d55.PNG)
- Title bị sai
- Không sử dụng cùng 1 kiểu design như thế này

**Comment by doannguyenminhchi** [comment]
Done

**Comment by tranquang9a1** [comment]
Fix lại
- Left panel cho nhỏ hơn
- Tab nào đang active thì cho màu đậm hẳn lên
- Khoảng trắng bên phải để làm gì ?
- Equipment image cho gần với nút hơn

![capture](https://cloud.githubusercontent.com/assets/6778102/8911755/a54f556e-34b8-11e5-94cb-1e4929eb4e89.PNG)

**Comment by doannguyenminhchi** [comment]
"Left panel cho nhỏ hơn" => khó xem notify
"Khoảng trắng bên phải để làm gì ?" => thì tui không biết điền gì nên mới đưa mấy cái nút xuống cho nó đầy! Chứ biết bỏ gì đâu(trên mobile phần report cũng nhiêu đấy) nó khá nhỏ không đủ gì cả!

**Comment by tranquang9a1** [comment]
Nếu vậy thì để khoảng trắng làm gì ? Cho cái form nó to ra hẳn luôn

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/9000910/a89641b0-3779-11e5-88cc-f9f3dce606f5.png)

**Comment by tranquang9a1** [comment]
Done
