### ISSUE TITLE
[Web] - Implement giao diện trang cho admin

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#43]
![capture24](https://cloud.githubusercontent.com/assets/6778102/8876619/ffc84be2-324a-11e5-981a-b5f27f61c143.PNG)

Đổi mới hoàn toàn

**Comment by ChiDNMSE60717** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/9121397/43a8e9e6-3cac-11e5-9cae-3ef9dc639374.png)

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/9121448/84ce27ba-3cac-11e5-99b0-a576721ecc0b.png)
