### ISSUE TITLE
[Web] - Trang Loại Học cần design lại 

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#44]
![capture9](https://cloud.githubusercontent.com/assets/6778102/8889352/fd2b2fb0-3300-11e5-9101-23b40f430487.PNG)

Title là chữ tiếng việt, có dấu, có nghĩa

**Comment by hungtvse61019** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/12387243/8889707/a9569cb2-330f-11e5-870f-06708da86284.png)

**Comment by tranquang9a1** [comment]
DOne
