### ISSUE TITLE
[Web] - Sửa giao diện trang cấu hình tiết học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#48]
- Title của trang không phải là link
- Textbox số phút nhỏ hơn.
- Background giống như đang bị đè lên, Tại sao lại có 2 scrollbar ?

![capture12](https://cloud.githubusercontent.com/assets/6778102/8890205/8c7cde28-3321-11e5-9fc4-0fa124aac363.PNG)
- Thống nhất không sử dụng alert, chỉ sử dụng 1 kiểu confirm box
  ![capture13](https://cloud.githubusercontent.com/assets/6778102/8890210/c29b8f22-3321-11e5-9ac5-02621e4866fa.PNG)
- Slot là gì ? Sao lại sử dụng tiếng nước ngoài

![capture2](https://cloud.githubusercontent.com/assets/6778102/8890236/9a86c302-3322-11e5-845e-a7366fd234d3.PNG)
- <b> Từ trang cấu hình, không thể quay về trang Thông Báo được <b>

**Comment by hungtvse61019** [comment]
Đã fix

**Comment by tranquang9a1** [comment]
Done
