### ISSUE TITLE
[Web] - Validate nhập số phút trong trang cấu hình tiết học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#49]
- Tại form nhập số phút
- Lần 1: Nhập sai

![capture](https://cloud.githubusercontent.com/assets/6778102/8890227/497a7076-3322-11e5-86fa-dd6ff26a1fa4.PNG)
- Lần 2: Nhập đúng

![capture1](https://cloud.githubusercontent.com/assets/6778102/8890228/4f426838-3322-11e5-8068-b5ed5e8aed6c.PNG)
- Kết quả 

![capture2](https://cloud.githubusercontent.com/assets/6778102/8890230/60f50ee6-3322-11e5-9a2c-29cf5533b754.PNG)

**Comment by hungtvse61019** [comment]
đã fix
![image](https://cloud.githubusercontent.com/assets/12387243/8892556/c73dfcde-3387-11e5-921a-fc6fdc2c6620.png)
![image](https://cloud.githubusercontent.com/assets/12387243/8892558/d4642ac8-3387-11e5-93d7-dbc2b5185733.png)

**Comment by tranquang9a1** [comment]
Design lại giao diện của alert "Nhập số phút mỗi tiết"

**Comment by tranquang9a1** [comment]
@ChiDNMSE60717 fix bug này.
Hiện tại  alert "Nhập số phút mỗi tiết" đang quá nhỏ, tăng kích cỡ font chữ cũng như size text box

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/8942774/859e2c42-35a1-11e5-9dc4-8cf8c8a8ef30.png)

**Comment by tranquang9a1** [comment]
Done
