### ISSUE TITLE
[Web] - Validate user gửi báo cáo

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#50]
- User không có tiết dạy nào trong ngày thì nút "Tạo Báo Cáo" phải disable

![capture](https://cloud.githubusercontent.com/assets/6778102/8890250/255d843e-3323-11e5-94f4-eb5c5c2c9e6c.PNG)

**Comment by doannguyenminhchi** [comment]
Done

**Comment by tranquang9a1** [comment]
Ở đâu ra quyền dev có thể close issue vậy

**Comment by doannguyenminhchi** [comment]
Không biết!

**Comment by tranquang9a1** [comment]
Done
