### ISSUE TITLE
[Web] - Lỗi hiển thị khi xóa equipment

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#51]
- Từ trang quản lí equipment tạo mới 1 equipment
- Xóa equipment vừa tạo, message ở confirm box bị sai

![capture](https://cloud.githubusercontent.com/assets/6778102/8892742/49abc7de-3395-11e5-9361-162bc816e9b9.PNG)

**Comment by tranquang9a1** [comment]
Khi thiết bị chưa được gắn vào phòng thì message phải khác
@ChiDNMSE60717 giúp @hungtvse61019  fix bug này

**Comment by doannguyenminhchi** [comment]
Đã fix! Nhưng trong trường hợp không thuộc phòng nào thì hiện tại đang xóa nên có thể phát sinh lỗi! Vì chưa có trạng thái disable cho equipment.

**Comment by tranquang9a1** [comment]
Lỗi, chưa test được. Check server biết lỗi chi tiết
http://128.199.208.93/

Làm xong nhớ assign lại cho dễ check

**Comment by tranquang9a1** [comment]
Done
