### ISSUE TITLE
[Web] - Implement function thống kê

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#53]
Xóa phần thống kê hiện tại
Implement chức năng như sau.

Thống kê số lượng phòng được đổi theo từng tháng trong 1 năm

**Comment by doannguyenminhchi** [comment]
Coi sơ cho xin cái ý kiến!

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/9115278/6c3ee7ee-3c88-11e5-91ba-8ad244332296.png)
