### ISSUE TITLE
[Web] - Sửa giao diện trang cập nhật thông tin thiết bị phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#54]
- Default cho mỗi equipment là tên thiết bị đầu tiên
- Thêm padding giữa nút cập nhật và textbox;

![capture](https://cloud.githubusercontent.com/assets/6778102/8892788/af3278a8-3397-11e5-8d47-43996ef19d9f.PNG)

**Comment by tranquang9a1** [comment]
Bug này chưa được fix
@ChiDNMSE60717  giúp @hungtvse61019  fix bug này nhé

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/8942315/e165b94e-359e-11e5-884e-d9ab4730d3ee.png)

![image](https://cloud.githubusercontent.com/assets/12387275/8942371/32e46d7e-359f-11e5-8ef1-56f8a361d2cc.png)

Do khác database nên xóa data và insert lại thì thấy khác nhiều lỗi khi tạo phòng và loại phòng. Nên chưa thể sửa dc!

**Comment by hungtvse61019** [comment]
không cần sửa nữa, đã thay đổi cách load
