### ISSUE TITLE
[Web] - Chỉnh giao diện phần create room type

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#61]
Cấu trúc thay đổi nên đổi giao diện phần room type. Update code, hoặc lên server check giao diện hiện tại để thay đổi mới

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/9113991/ac90d700-3c81-11e5-959e-b7b709c8ddfd.png)
Vậy dc chưa!?
Khi đổi số hàng số ghế ở dãy 1 cũng sẽ update cho mấy dãy sau rồi!
