### ISSUE TITLE
[Web] - Lỗi giao diện trang chỉnh sửa phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#64]
- Khi chỉnh sửa phòng thì tên nút không phải là "Tạo Phòng"
- Khoảng cách từ text đến textbox gần hơn
  ![capture](https://cloud.githubusercontent.com/assets/6778102/9012395/9c1cc20a-37de-11e5-8fce-b2bc116bb65f.PNG)

**Comment by hungtvse61019** [comment]
Đã fix
![image](https://cloud.githubusercontent.com/assets/12387243/9014992/179afd8c-37f0-11e5-9318-4bb0924c94c1.png)

**Comment by tranquang9a1** [comment]
Done
