### ISSUE TITLE
[Web] - Implement chức năng chỉnh sửa phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#65]
Hiện tại lúc chỉnh sửa đang là thêm phòng học mới, không phải update phòng hiện tại

**Comment by hungtvse61019** [comment]
Không hiểu

**Comment by tranquang9a1** [comment]
Vào chỉnh sửa phòng học. Nó ko update phòng hiện tại mà tạo ra phòng mới

**Comment by hungtvse61019** [comment]
Đã fix\
At revision: 397

**Comment by tranquang9a1** [comment]
Done
