### ISSUE TITLE
[Web] - Sửa giao diện trang tạo thiết bị

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#67]
![capture](https://cloud.githubusercontent.com/assets/6778102/9012447/2945037c-37df-11e5-9ebb-03d1a05fb927.PNG)
- Thừa 1 text box không biết để làm gì
- Thêm padding bottom cho dễ nhìn
- Đồng thời sửa ở chỗ nào xài form này

**Comment by hungtvse61019** [comment]
đã fix
![image](https://cloud.githubusercontent.com/assets/12387243/9014093/58a0e810-37ea-11e5-9dab-c3d43e5a2f37.png)

**Comment by tranquang9a1** [comment]
Done
