### ISSUE TITLE
[Web] - Lỗi khi tạo thiết bị

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#68]
- Nhập data

![capture](https://cloud.githubusercontent.com/assets/6778102/9012509/aa8c8fae-37df-11e5-87ff-b2f28e12f671.PNG)
- Submit form

![capture1](https://cloud.githubusercontent.com/assets/6778102/9012514/afd9f654-37df-11e5-9ff0-a54eaf806646.PNG)

**Comment by hungtvse61019** [comment]
Đã fix 
At revision: 395

**Comment by tranquang9a1** [comment]
Vẫn không tạo được
![capture](https://cloud.githubusercontent.com/assets/6778102/9024749/164f176c-390b-11e5-8d36-52d9cdf5d625.PNG)
![capture1](https://cloud.githubusercontent.com/assets/6778102/9024750/18d76142-390b-11e5-9fdf-e2c7bc8975d2.PNG)

**Comment by hungtvse61019** [comment]
Đã fix
At revision: 401

**Comment by tranquang9a1** [comment]
Done
