### ISSUE TITLE
[Web] - Sửa giao diện form cập nhật loại thiết bị

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#69]
![capture](https://cloud.githubusercontent.com/assets/6778102/9012539/e520bb2c-37df-11e5-8db7-b75c4de68088.PNG)
- Căn lề lại
- Giảm khoảng cách từ text đến input

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/9031472/af847256-39dd-11e5-8a25-201ce28849da.png)
Không nên thu giảm khoảng cách dễ ảnh hưởng các form khác
