### ISSUE TITLE
[Web] - Lỗi khi tạo phòng học mới

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#74]
Tạo Phòng Học mới
- Chỉ nhập tên phòng -> Tạo Phòng -> Validate đúng

![capture2](https://cloud.githubusercontent.com/assets/6778102/9024766/88f45510-390c-11e5-80e9-8cefe83e6412.PNG)
- Sau đó chọn loại phòng -> Tạo Phòng -> Validate sai

![capture1](https://cloud.githubusercontent.com/assets/6778102/9024769/b2609e4a-390c-11e5-95ee-607dd5576b88.PNG)

**Comment by hungtvse61019** [comment]
Đã fix
At revision: 400

**Comment by tranquang9a1** [comment]
Done
