### ISSUE TITLE
[Web] - Sửa giao diện trang Phòng Học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#75]
Tự dưng để khoảng trắng làm gì

![capture](https://cloud.githubusercontent.com/assets/6778102/9024773/3b20c1c4-390d-11e5-8797-b2fb1002b72a.PNG)

**Comment by hungtvse61019** [comment]
Đã fix
At revision: 409
![image](https://cloud.githubusercontent.com/assets/12387243/9027178/ec5a2f86-3974-11e5-997e-ecc41f8409da.png)
