### ISSUE TITLE
[Web] - Sửa hiển thị trang phòng học

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#77]
Phòng học load lên phải được order theo số phòng hoặc order theo trạng thái

**Comment by hungtvse61019** [comment]
Đã order theo update time
At revision: 408

**Comment by tranquang9a1** [comment]
http://128.199.208.93/staff/classroom?ACTIVETAB=tab1&MESSAGE=0
Lỗi
