### ISSUE TITLE
[Web]  -  Check lỗi trang jsp

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#84]
Trong các trang quản lí phòng học, quản lí thiết bị
window.history.pushState({"html":'',"pageTitle":''},"", "http://localhost:8080/staff/equipment?ACTIVETAB=" + tab);

Code trang jsp có dòng này là sao. Set cứng localhost ?

**Comment by doannguyenminhchi** [comment]
cai nay de update URL khi chuyen tab. De tui sua lai!

**Comment by doannguyenminhchi** [comment]
Done
