### ISSUE TITLE
[Web] - Design lại trang thông báo của staff

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#86]
[Web] - Design lại trang thông báo của staff
Hiện tại đang trống bên phải nhiều quá

**Comment by doannguyenminhchi** [comment]
Đang thêm thông báo của hệ thống(Thiết bị hết thời hạn bảo hành, hay số lượt phòng được đổi khi chạy cronjob vào các mốc thời gian) được không

**Comment by tranquang9a1** [comment]
OK. Làm chạy thử đã

**Comment by doannguyenminhchi** [comment]
![image](https://cloud.githubusercontent.com/assets/12387275/9260731/af2051d2-4233-11e5-8b83-973e83646b9a.png)
Sửa cái notify cho nhiều trang cùng lúc rùi!
