### ISSUE TITLE
[Document] - Viết System Testing Test case

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#89]
Viết test cho các module sau:
- Thêm xóa sửa equipment
- Thêm xóa sửa equipment category
- Thêm xóa sửa room type
- Thêm xóa sửa classroom

Sử dụng template ở đây: https://github.com/tranquang9a1/ECRM/blob/master/Document/TemplateTesting.xlsx

**Comment by doannguyenminhchi** [comment]
Viết rồi!
