### ISSUE TITLE
[Web] - Lỗi khi tạo thiết bị

### ISSUE THREAD

**Issue by tranquang9a1** [tranquang9a1/ECRM#91]
Ở tab loại thiết bị, Tên loại "Empty" có quản lí
Khi tạo thiết bị. Loại này không được load lên

**Comment by hungtvse61019** [comment]
Loại này lúc đầu tạo ra có ý nghĩa là khi xóa loại thiết bị khác, thiết bị liên quan sẽ update về empty, nhưng giờ không làm vậy nữa
